{{- range $index := .Values.cronjobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  {{- toYaml .taskParmeters | nindent 2 }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .name }}
            {{- toYaml .container | nindent 12 -}}
            {{ if .env }}
            env: {{ toYaml .env | nindent 14 -}}
            {{- end -}}
            {{ if .volumeMounts }}
            volumeMounts: {{ toYaml .volumeMounts | nindent 14 }}
            {{- end }}
          restartPolicy: {{ .restartPolicy }}
          {{ if .volumes -}}
          volumes: {{ toYaml .volumes | nindent 12 -}}
          {{- end -}}
{{- end }}
