apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.name }}
  namespace: {{ .Values.namespace }}
spec:
  {{- toYaml .Values.cronjob.taskParmeters | nindent 2 }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Values.cronjob.name }}
            {{- toYaml .Values.cronjob.container | nindent 12 -}}
            {{ if .Values.cronjob.env }}
            env: {{ toYaml .Values.cronjob.env | nindent 14 -}}
            {{- end -}}
            {{ if .Values.cronjob.volumeMounts }}
            volumeMounts: {{ toYaml .Values.cronjob.volumeMounts | nindent 14 }}
            {{- end }}
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
          {{ if .Values.cronjob.volumes -}}
          volumes: {{ toYaml .Values.cronjob.volumes | nindent 12 -}}
          {{- end -}}